name: net_cloak
description: "A Free VPN App "
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flex_color_scheme: ^8.0.2
  shared_preferences: ^2.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_assets:
    assets_path: assets/
    output_path: lib/constants/
    filename: assets.dart
    field_prefix: 
    
flutter:
  uses-material-design: true
  assets:
    - assets/